version: '3'
services:
  php-fpm:
    build:
      context: docker/php-fpm
    container_name: ${APP_NAME:?err}-php
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
  nginx:
    build:
      context: docker/nginx
    container_name: ${APP_NAME:?err}-nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - internal
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME:?err}-mysql
    ports:
      - '3306:3306'
    restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?err}
    volumes:
      - ./mysql_db:/var/lib/mysql
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28